version: '3'
services:
  app:
    image: node:18
    working_dir: /app
    command: bash
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true