version: '3'
services:
  app:
    image: node:16
    working_dir: /app
    command: bash -c "npm install && npm start"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
