INSERT INTO auteur(id,nom,prenom) VALUES(1,'Dostoevski','Fdor');
INSERT INTO auteur(id,nom,prenom) VALUES(2,'Semprun','Jorge');
INSERT INTO auteur(id,nom,prenom) VALUES(3,'Tolsto','Leon');
INSERT INTO auteur(id,nom,prenom) VALUES(4,'Steinbeck','John');
INSERT INTO auteur(id,nom,prenom) VALUES(5,'Ferro','Marc');
INSERT INTO auteur(id,nom,prenom) VALUES(6,'Stocker','Bram');
INSERT INTO auteur(id,nom,prenom) VALUES(7,'Shelley','Marie');
INSERT INTO auteur(id,nom,prenom) VALUES(8,'King','Stephen');
INSERT INTO auteur(id,nom,prenom) VALUES(9,'Grass','Gunter');
INSERT INTO auteur(id,nom,prenom) VALUES(10,'Barjavel','Ren');
INSERT INTO auteur(id,nom,prenom) VALUES(11,'Simmons','Dan');
INSERT INTO auteur(id,nom,prenom) VALUES(12,'Herbert','Frank');
INSERT INTO auteur(id,nom,prenom) VALUES(13,'Clarke','Arthur C.');
INSERT INTO auteur(id,nom,prenom) VALUES(14,'Bradbury','Ray');
INSERT INTO auteur(id,nom,prenom) VALUES(15,'Dick','Philip K.');
INSERT INTO auteur(id,nom,prenom) VALUES(16,'Orwell','Georges');
INSERT INTO auteur(id,nom,prenom) VALUES(17,'Hugo','Victor');
INSERT INTO auteur(id,nom,prenom) VALUES(18,'Zola','Emile');
INSERT INTO auteur(id,nom,prenom) VALUES(19,'Morris','Damien');
INSERT INTO auteur(id,nom,prenom) VALUES(20,'Flaubert','Gustave');
INSERT INTO auteur(id,nom,prenom) VALUES(21,'Asimov','Isaac');
INSERT INTO auteur(id,nom,prenom) VALUES(22,'Miller','Frank');
INSERT INTO auteur(id,nom,prenom) VALUES(23,'Eco','Umberto');
INSERT INTO auteur(id,nom,prenom) VALUES(24,'Irving','John');
INSERT INTO auteur(id,nom,prenom) VALUES(25,'Braudel','Fernand');
INSERT INTO auteur(id,nom,prenom) VALUES(26,'Camus','Albert');
INSERT INTO auteur(id,nom,prenom) VALUES(27,'Vian','Boris');
INSERT INTO auteur(id,nom,prenom) VALUES(28,'Lehane','Dennis');
INSERT INTO auteur(id,nom,prenom) VALUES(29,'Oe','Kenzaburo');
INSERT INTO auteur(id,nom,prenom) VALUES(30,'Kertesz','Imre');
INSERT INTO auteur(id,nom,prenom) VALUES(31,'Garcia Marquez','Gabriel');
INSERT INTO auteur(id,nom,prenom) VALUES(32,'Pratt','Hugo');
INSERT INTO auteur(id,nom,prenom) VALUES(33,'Cooper','Fenimore');
