VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.define "database" do |db|
    db.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.56.100"
  end
  
  config.vm.define "web" do |web|
    web.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip: "192.168.56.101"
    web.vm.provision "shell",
      inline: "echo '127.0.0.1 localhost web01\n192.168.56.100 db01' > /etc/hosts"
  end
end

